### ISSUE TITLE
No arrow on select when $form-is-select is false

### ISSUE THREAD

**Issue by kloh-fr** [kloh-fr/formage#1]
If `$form-is-select` is false, there is no arrow at all on select tag.

Root cause is from the following lines:
```scss
/* Avoid browser applying its styles */
#{$form-fields},
#{$form-buttons} {
    -webkit-appearance: none;
    -moz-appearance: none;
}
```

To do: exclude `select` from `$form-fields` variable selector.
