### ISSUE TITLE
Fields width at 100%

### ISSUE THREAD

**Issue by kloh-fr** [kloh-fr/formage#2]
Right now width of fields is fixed at `100%` in all case:
```scss
input,
button,
select,
textarea {
    padding: $form-input-padding;
    width: 100%;
```
But in some cases we don't want that (for instance if we use a `select` tag for a lang switcher).
The idea is to specify a 100% width only if we're in a form or a fieldset:

```scss
form,
.form,
fieldset,
.fieldset {
    input,
    button,
    select,
    textarea {
        width: 100%;
    }
}
``` 
Note: be careful with buttons.
